name: Deploy

on:
  push:
    branches:
      - dev
      - main

jobs:
  staging_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build --outdir dist/
      - name: Copy package via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.STAGING_HOST }}
          USERNAME: ${{ secrets.STAGING_USERNAME }}
          PORT: ${{ secrets.STAGING_PORT }}
          KEY: ${{ secrets.STAGING_SSHKEY }}
        with:
          source: "dist/moov-*.tar.gz"
          target: "/home/moovuser"
      - name: Install package
        uses: appleboy/ssh-action@master
        env:
          HOST: ${{ secrets.STAGING_HOST }}
          USERNAME: ${{ secrets.STAGING_USERNAME }}
          PORT: ${{ secrets.STAGING_PORT }}
          KEY: ${{ secrets.STAGING_SSHKEY }}
        with:
          script: ls -lh
  dev_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v3
      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
        with:
          source: "."
          target: "/home/ubuntu/moov-web"
